"""student table

Revision ID: 70010a6ce74d
Revises: d4b4752af6dd
Create Date: 2026-03-11 14:02:02.038171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70010a6ce74d'
down_revision = 'd4b4752af6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stu_password', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('stu_password')

    # ### end Alembic commands ###
