"""author-table

Revision ID: d86d37fc46bd
Revises: 09fc379c9f57
Create Date: 2026-03-13 10:23:03.040217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86d37fc46bd'
down_revision = '09fc379c9f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_age', sa.DateTime(), nullable=False),
    sa.Column('author_email', sa.String(length=100), nullable=True),
    sa.Column('author_phone', sa.String(length=11), nullable=False),
    sa.Column('author_password', sa.String(length=200), nullable=False),
    sa.Column('author_address', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_email'),
    sa.UniqueConstraint('author_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
