"""student table

Revision ID: f74e1fc21543
Revises: 
Create Date: 2026-03-09 15:09:27.523347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74e1fc21543'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_name', sa.String(length=100), nullable=False),
    sa.Column('stu_age', sa.DateTime(), nullable=False),
    sa.Column('stu_email', sa.String(length=100), nullable=True),
    sa.Column('stu_phone', sa.String(length=10), nullable=False),
    sa.Column('stu_address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stu_email'),
    sa.UniqueConstraint('stu_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
